"""modified-list-items

Revision ID: 12df8ff96b04
Revises: fc07a76dbe2f
Create Date: 2023-05-08 09:32:36.587521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12df8ff96b04'
down_revision = 'fc07a76dbe2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('List_Items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.Column('price_unit', sa.String(length=4), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('grand_price', sa.Integer(), nullable=True),
    sa.Column('registered_by', sa.Integer(), nullable=True),
    sa.Column('registered_at', sa.String(length=200), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['registered_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Food_Items')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Food_Items',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('status', sa.VARCHAR(length=10), nullable=True),
    sa.Column('price_unit', sa.VARCHAR(length=4), nullable=True),
    sa.Column('price', sa.INTEGER(), nullable=True),
    sa.Column('quantity', sa.INTEGER(), nullable=True),
    sa.Column('grand_price', sa.INTEGER(), nullable=True),
    sa.Column('registered_by', sa.INTEGER(), nullable=True),
    sa.Column('registered_at', sa.VARCHAR(length=200), nullable=True),
    sa.Column('updated_by', sa.INTEGER(), nullable=True),
    sa.Column('updated_at', sa.VARCHAR(length=200), nullable=True),
    sa.ForeignKeyConstraint(['registered_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('List_Items')
    # ### end Alembic commands ###
