"""modified-list

Revision ID: 2e2c2711ac7b
Revises: 12df8ff96b04
Create Date: 2023-05-08 10:32:25.649352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e2c2711ac7b'
down_revision = '12df8ff96b04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('List_Items', schema=None) as batch_op:
        batch_op.alter_column('grand_price',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('List_Items', schema=None) as batch_op:
        batch_op.alter_column('grand_price',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
